version: '3.2'
networks:
  cluster:
    driver: bridge
services:
  nfs:
    image: joebiellik/nfs4
    container_name: nfs_hipchat
    privileged: true
    ports:
      - "2049:2049/tcp"
      - "2049:2049/udp"
      - "111:111/tcp"
      - "111:111/udp"
    volumes:
      - $HOME/dockerdata/nfs_hipchat/nfs-export-cfg:/etc/exports
      - $HOME/dockerdata/nfs_hipchat/:/mnt
  redis-master:
    image: redis:3.2
    container_name: rds_hipchat_master
    ports:
      - "6379:6379"
    volumes:
      - $HOME/dockerdata/rds_hipchat:/data
  redis-slave1:
    image: redis:3.2
    container_name: rds_hipchat_slave1
    command: redis-server --slaveof redis-master 6379
    links:
      - redis-master
  redis-slave2:
    image: redis:3.2
    container_name: rds_hipchat_slave2
    command: redis-server --slaveof redis-master 6379
    links:
      - redis-master
  sentinal:
    build: sentinal
    container_name: sentinal_hipchat
    environment:
      - SENTINAL_DOWN_AFTER=1000
      - SENTINAL_FAILOVER=1000
    links:
      - redis-master
      - redis-slave1
      - redis-slave2
  pgmaster:
    build:
      context: ./pgsql
      dockerfile: Postgres-9.5.Dockerfile
#    container_name: pgmaster
    environment:
      - PARTNER_NODES=pgmaster,pgslave1
      - NODE_ID=1
      - NODE_NAME=node1
      - CLUSTER_NODE_NETWORK_NAME=pgmaster
      - NODE_PRIORITY=100
      - SSH_ENABLE=1
      - POSTGRES_PASSWORD=hipchat
      - POSTGRES_DB=hipchat
      - POSTGRES_USER=hipchat
      - CLEAN_OVER_REWIND=0
      - CONFIGS="listen_addresses:'*',max_replication_slots:5"
      - CLUSTER_NAME=pg_cluster
      - REPLICATION_DB=hipchat
      - REPLICATION_USER=hipchat
      - REPLICATION_PASSWORD=hipchat
    links:
      - pgslave1
      - pgpool
    ports:
      - "5432:5432"
    volumes:
      - $HOME/dockerdata/psql_hipchat:/var/lib/postgresql/data
    networks:
      cluster:
        aliases:
          - pgmaster
  pgslave1:
    build:
      context: ./pgsql
      dockerfile: Postgres-9.5.Dockerfile
#    container_name: pgslave1
    environment:
      - PARTNER_NODES=pgmaster
      - REPLICATION_PRIMARY_HOST=pgmaster
      - NODE_ID=2
      - NODE_NAME=node2
      - CLUSTER_NODE_NETWORK_NAME=pgslave1
      - CLEAN_OVER_REWIND=1
      - CONFIGS="max_replication_slots:10"
    ports:
      - "5441:5432"
    volumes:
      - $HOME/dockerdata/psql_hipchat:/var/lib/postgresql/data
    networks:
      cluster:
        aliases:
          - pgslave1
#  pgslave2:
#    build:
#      context: ./pgsql
#      dockerfile: Postgres-9.5.Dockerfile
#    container_name: slave2
#    environment:
#      - PARTNER_NODES="pgmaster,pgslave1"
#      - REPLICATION_PRIMARY_HOST=pgmaster
#      - NODE_ID=3
#      - NODE_NAME=node3
#      - CLUSTER_NODE_NETWORK_NAME=pgslave2
#      - CLEAN_OVER_REWIND=1
#      - CONFIGS="max_replication_slots:10"
#    ports:
#        - "5442:5432"
#    volumes:
#      - $HOME/dockerdata/psql_hipchat:/var/lib/postgresql/data
#    networks:
#      cluster:
#        aliases:
#          - pgslave2
  pgpool:
    build:
      context: ./pgsql
      dockerfile: Pgpool-latest.Dockerfile
    environment:
      - PCP_USER=pcp_user
      - PCP_PASSWORD=pcp_pass
      - WAIT_BACKEND_TIMEOUT=20
      - CHECK_USER=hipchat
      - CHECK_PASSWORD=hipchat
      - CHECK_PGCONNECT_TIMEOUT=3
      - SSH_ENABLE=1
      - DB_USERS=hipchat:hipchat
      - BACKENDS="0:pgmaster:5432:1/var/lib/postgresql/data:ALLOW_TO_FAILOVER,1:pgslave1::::,2:pgslave2::::"
      - REQUIRE_MIN_BACKENDS=2
      - CONFIGS="num_init_children:250,max_pool:4"
    ports:
      - "5430:5432"
      - "9898:9898"
    networks:
      cluster:
        aliases:
          - pgpool
  haproxy:
    image: haproxy_dev
    container_name: ha_hipchat
    ports:
      - "1936:1936"
      - "666:666"