version: '3'
networks:
  cluster:
    driver: bridge
services:
  nfs:
    image: joebiellik/nfs4
    container_name: nfs_hipchat
    privileged: true
    ports:
      - "2049:2049/tcp"
      - "2049:2049/udp"
      - "111:111/tcp"
      - "111:111/udp"
    volumes:
      - $HOME/dockerdata/nfs_hipchat/nfs-export-cfg:/etc/exports
      - $HOME/dockerdata/nfs_hipchat/:/mnt
  rdsmaster:
    image: redis:3.2
    container_name: rdsmaster
    ports:
      - "6379:6379"
    volumes:
      - $HOME/dockerdata/rds_hipchat:/data
  rdsslave1:
    image: redis:3.2
    container_name: rdsslave1
    command: redis-server --slaveof rdsmaster 6379
    links:
      - rdsmaster
  rdsslave2:
    image: redis:3.2
    container_name: rdsslave2
    command: redis-server --slaveof rdsmaster 6379
    links:
      - rdsmaster
  sentinal:
    build: sentinal
    container_name: rdssentinal
    environment:
      - SENTINAL_DOWN_AFTER=5
      - SENTINAL_FAILOVER=5
      - MASTER_HOST=rdsmaster
      - SENTINEL_QUORUM=1
    ports:
      - "9000:26379"
    links:
      - rdsmaster
      - rdsslave1
      - rdsslave2
  pgmasterhipchat:
    build:
      context: ./pgsql
      dockerfile: Postgres-9.5.Dockerfile
    container_name: pgmaster
    environment:
      - PARTNER_NODES=pgslave1,pgslave2
      - NODE_ID=1
      - NODE_NAME=node1
      - CLUSTER_NODE_NETWORK_NAME=pgmaster
      - NODE_PRIORITY=100
      - SSH_ENABLE=1
      - POSTGRES_PASSWORD=hipchat
      - POSTGRES_DB=hipchat
      - POSTGRES_USER=hipchat
      - CLEAN_OVER_REWIND=0
      - CONFIGS=max_replication_slots:15,max_connections:1000
      - CLUSTER_NAME=pg_cluster
      - REPLICATION_DB=replication_db
      - REPLICATION_USER=replication_user
      - REPLICATION_PASSWORD=replication_pass
    ports:
      - "5432:5432"
    volumes:
      - $HOME/dockerdata/pgmaster:/var/lib/postgresql/data
    networks:
      cluster:
        aliases:
          - pgmaster
  pgslave1_hipchat:
    build:
      context: ./pgsql
      dockerfile: Postgres-9.5.Dockerfile
    container_name: pgslave1_hipchat
    environment:
      - PARTNER_NODES=pgmaster,pgslave2
      - REPLICATION_PRIMARY_HOST=pgmaster
      - NODE_ID=2
      - NODE_NAME=node2
      - CLUSTER_NODE_NETWORK_NAME=pgslave1
      - CLEAN_OVER_REWIND=1
      - CONFIGS=max_replication_slots:10
    ports:
      - "5441:5432"
    networks:
      cluster:
        aliases:
          - pgslave1
  pgslave2_hipchat:
    build:
      context: ./pgsql
      dockerfile: Postgres-9.5.Dockerfile
    container_name: pgslave2_hipchat
    environment:
      - PARTNER_NODES=pgmaster,pgslave1
      - REPLICATION_PRIMARY_HOST=pgmaster
      - NODE_ID=3
      - NODE_NAME=node3
      - CLUSTER_NODE_NETWORK_NAME=pgslave2
      - CLEAN_OVER_REWIND=1
      - CONFIGS=max_replication_slots:10
    ports:
        - "5442:5432"
    networks:
      cluster:
        aliases:
          - pgslave2
  pgpool1_hipchat:
    build:
      context: ./pgsql
      dockerfile: Pgpool-latest.Dockerfile
    container_name: pgpool1_hipchat
    environment:
      - PCP_USER=pcp_user
      - PCP_PASSWORD=pcp_pass
      - WAIT_BACKEND_TIMEOUT=20
      - CHECK_USER=replication_user
      - CHECK_PASSWORD=replication_pass
      - CHECK_PGCONNECT_TIMEOUT=5
      - SSH_ENABLE=1
      - DB_USERS=replication_user:replication_pass
      - BACKENDS=0:pgmaster:5432:1:/var/lib/postgresql/data:ALLOW_TO_FAILOVER,1:pgslave1:5432:1:/var/lib/postgresql/data:ALLOW_TO_FAILOVER,2:pgslave2:5432:2:/var/lib/postresql/data:ALLOW_TO_FAILOVER
      - REQUIRE_MIN_BACKENDS=1
      - CONFIGS=num_init_children:250,max_pool:15,use_watchdog:on,other_pgpool_hostname1:pgpool2,other_pgpool_port1:5432,other_wd_port1:9006,wd_port:9005,wd_hostname:pgpool1,wd_heartbeat_port:9694,heartbeat_destination0:pgpool2
    ports:
      - "5430:5432"
      - "9898:9898"
      - "9005:9005"
      - "9694:9694"
    networks:
      cluster:
        aliases:
          - pgpool1
  pgpool2_hipchat:
    build:
      context: ./pgsql
      dockerfile: Pgpool-latest.Dockerfile
    container_name: pgpool2_hipchat
    environment:
      - PCP_USER=pcp_user
      - PCP_PASSWORD=pcp_pass
      - WAIT_BACKEND_TIMEOUT=20
      - CHECK_USER=replication_user
      - CHECK_PASSWORD=replication_pass
      - CHECK_PGCONNECT_TIMEOUT=5
      - SSH_ENABLE=1
      - DB_USERS=replication_user:replication_pass
      - BACKENDS=0:pgmaster:5432:1:/var/lib/postgresql/data:ALLOW_TO_FAILOVER,1:pgslave1:5432:1:/var/lib/postgresql/data:ALLOW_TO_FAILOVER,2:pgslave2:5432:2:/var/lib/postresql/data:ALLOW_TO_FAILOVER
      - REQUIRE_MIN_BACKENDS=1
      - CONFIGS=num_init_children:250,max_pool:15,use_watchdog:on,other_pgpool_hostname1:pgpool1,other_pgpool_port1:5432,other_wd_port1:9005,wd_port:9006,wd_hostname:pgpool2,wd_heartbeat_port:9695,heartbeat_destination0:pgpool1
    ports:
      - "5431:5432"
      - "9899:9898"
      - "9006:9006"
      - "9695:9695"
    networks:
      cluster:
        aliases:
          - pgpool2
  haproxy:
    image: haproxy_dev
    container_name: ha_hipchat
    ports:
      - "1936:1936"
      - "666:666"